# Generated by Django 5.0.4 on 2024-04-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_university_batch_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='name',
            new_name='batch',
        ),
    ]
